# Generated by Django 3.0.3 on 2020-03-06 15:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djafforum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
