# Generated by Django 3.0.3 on 2020-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djafforum', '0002_auto_20200306_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(),
        ),
    ]
