# Generated by Django 2.2.10 on 2020-03-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200324_0939'),
        ('djafforum', '0005_auto_20200324_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
