# Generated by Django 2.2.10 on 2020-03-21 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_homepage.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djafforum', '0004_auto_20200309_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_followed', models.BooleanField(default=False)),
                ('followed_on', models.DateField(blank=True, null=True)),
                ('no_of_votes', models.IntegerField(default='0')),
                ('no_of_down_votes', models.IntegerField(default='0')),
                ('is_like', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_topic', to='djafforum.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_topic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('used_votes', models.IntegerField(default='0')),
                ('user_roles', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Publisher', 'Publisher')], max_length=10)),
                ('profile_pic', models.FileField(blank=True, max_length=500, null=True, upload_to=django_homepage.users.models.img_url)),
                ('send_mailnotifications', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
