# Generated by Django 2.2.10 on 2020-03-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djafforum', '0005_auto_20200324_0106'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(to='djafforum.Badge'),
        ),
    ]
