# Generated by Django 2.2.4 on 2020-04-06 09:03

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=500)),
                ('github_profile_link', models.URLField(help_text='Your github profile link')),
                ('mobile_number', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=500)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_project_link', models.URLField(help_text='Link to your project on Github')),
                ('project_url', models.URLField(help_text='Project URL')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.Contact')),
            ],
        ),
    ]
