# Generated by Django 2.2.4 on 2020-04-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='business_name',
        ),
    ]
